### ISSUE TITLE
When try to login github, it gives error.

### ISSUE THREAD

**Issue by enesygt** [dragfire/leetup#24] opened 2020-11-09 05:48 UTC
⢺ Logging in...thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/service/auth.rs:137:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I got this. error. When I try to login. with "leetup user -g"

**Comment by dragfire** [comment] 2020-11-09 06:01
That's strange! It's working on my side. Can you try installing the latest version: 0.1.13?

**Comment by dragfire** [comment] 2020-11-09 06:09
Nevertheless I should remove all those `unwrap`s and handle it properly. Would accept a PR for that!

**Comment by enesygt** [comment] 2020-11-09 06:11
> That's strange! It's working on my side. Can you try installing the latest version: 0.1.13?

Thanks for answer. I am checking now.

**Comment by enesygt** [comment] 2020-11-09 06:17
⡗ Logging in...thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/service/auth.rs:137:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I got the new version but the problem continues.

**Comment by dragfire** [comment] 2020-11-09 06:29
If you have the repo cloned, can you run `RUST_LOG=info cargo run — user -g` and paste the output here. I am not able to reproduce the issue on my side.

**Comment by enesygt** [comment] 2020-11-09 06:43
This is the output:
⡧ Logging in...[2020-11-09T06:42:17Z INFO  leetup::service::auth] Status: 302 Found
[2020-11-09T06:42:17Z INFO  leetup::service::auth] Redirecting to: https://github.com/session
⡗ Logging in...[2020-11-09T06:42:17Z INFO  leetup::service::auth] Redirecting to: https://leetcode.com/accounts/github/login/?next=%2F
⢺ Logging in...[2020-11-09T06:42:18Z INFO  leetup::service::auth] Status: 302 Found
[2020-11-09T06:42:18Z INFO  leetup::service::auth] Redirecting to: https://github.com/login/oauth/authorize?client_id=6efe458dfe2230acceea&redirect_uri=https%3A%2F%2Fleetcode.com%2Faccounts%2Fgithub%2Flogin%2Fcallback%2F&scope=user%3Aemail&response_type=code&state=nxapovQHa2be
⡗ Logging in...[2020-11-09T06:42:18Z INFO  leetup::service::auth] Status: 200 OK
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/service/auth.rs:137:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by enesygt** [comment] 2020-11-09 06:50
That's ok now. Thank you a lot.

**Comment by dragfire** [comment] 2020-11-09 16:54
What was the issue and how did you fix it?

**Comment by enesygt** [comment] 2020-11-09 18:38
My problem is my leetcode account wasn't connected to my github account. I have connected my leetcode to github account and the problem fixed.

**Comment by dragfire** [comment] 2020-11-09 19:32
Glad that you fixed it. Closing the issue!

**Closed by dragfire** 2020-11-09 19:32 UTC
